<?php

/**
 * Implementation of hook_install().
 */
function css3pie_install() {
  if(!file_exists(libraries_get_path('PIE') . '/PIE.htc')) {
    drupal_set_message(t('PIE library missing. Download PIE library from http://css3pie.com/ and add it to sites/all/libraries/PIE.'),'error');
  }
}

/**
 * Implementation of hook_uninstall().
 */
function css3pie_uninstall() {
  db_query("DELETE FROM {variable} WHERE name LIKE 'css3pie_css_%'");
  drupal_rmdir(file_default_scheme() . '://css3pie');
}